language: android
jdk: oraclejdk8
android:
  components:
  - android-28
  - build-tools-27.0.3
addons:
  ssh_known_hosts: 167.99.94.185
  apt:
    packages:
    - sshpass

env:
  global:
  # install timeout in minutes (2 minutes by default)
  - ADB_INSTALL_TIMEOUT=8

before_install:
- yes | sdkmanager "platforms;android-27"
- chmod +x gradlew

# Run assemble and unit tests
script:
- ./gradlew clean testDebugUnitTest testDebugUnitTestCoverage
- cp rxfastrecyclerview/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml testDebugUnitTestCoverage.xml
after_success:
- bash <(curl -s https://codecov.io/bash)